server:
  port: 9011

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/booksystem?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: jj910712

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mp.entity
  global-config:
    db-config:
      id-type: auto

# logging
logging:
  level:
    root: warn
    com.mp.dao: trace


